controller:
  base_url: "http://127.0.0.1:8010"
  timeout_sec: 60

toolrunner:
  base_url: "http://127.0.0.1:8011"
  timeout_sec: 30
  shared_token: ""

ui:
  mode: "pretty"
  history_file: "../data/cli_history.txt"
  log_file: "../logs/cli.log"
  spinner: true            # false — если не применял мой фикс спиннера
  confirm_on_low_conf: false
  auto_exec: false
