config_version: 1

# Включает режим диагностики и эндпоинт /diagnostics
diagnostic_mode: false

server:
  host: "127.0.0.1"   # не светимся наружу
  port: 8010

model:
  name: "qwen2.5:1.5b"
  host: "127.0.0.1"
  port: 11434
  timeout_sec: 60
  keep_alive: "15m"
  profiles:
    balanced:
      num_predict: 160
      temperature: 0.5
      top_p: 0.9
      top_k: 40
      repeat_penalty: 1.1
      ctx: 1024
    smalltalk:
      num_predict: 160
      temperature: 0.7
      top_p: 0.9
      top_k: 40
      repeat_penalty: 1.08
      ctx: 1024
    tiny:
      num_predict: 96
      temperature: 0.3
      top_p: 0.9
      top_k: 40
      repeat_penalty: 1.1
      ctx: 768

sampling:
  temperature: 0.5
  top_p: 0.9
  top_k: 40
  repeat_penalty: 1.1
  num_predict: 160
  ctx: 1024

controller:
  proxy_commands: true    

toolrunner:
  base_url: "http://127.0.0.1:8011"
  timeout_sec: 30
  shared_token: ""          # задай позже; тогда контроллер будет слать X-Jarvis-Token

history:
  enabled: true
  path: "../data/history.jsonl"
  retention_days: 30
  max_bytes: 5000000        # 5 MB

logging:
  level: "INFO"
  file: "../logs/controller.log"
  rotate_mb: 10
  backups: 5
  
interaction:
  enabled: true
  resolver_url: "http://127.0.0.1:8020"
  resolver_mode: "hybrid"
  llm_threshold: 0.75
  use_legacy_when_low_conf: true
  low_conf_threshold: 0.50
  llm:
    enable: true
    base_url: "http://127.0.0.1:11434"
    model: "qwen2.5:1.5b"
